services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
      target: PGASGRAPH_DEVELOPMENT
    tty: true
    stdin_open: true
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/workspace/pgasgraph
  deploy:
    build:
      context: .
      dockerfile: Dockerfile
      target: PGASGRAPH_BUILD_INSTALL
 
